// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PhaseType 游戏阶段
type PhaseType int32

const (
	PhaseType_PHASE_TYPE_UNSPECIFIED PhaseType = 0
	PhaseType_PHASE_TYPE_START       PhaseType = 10
	// 夜晚阶段 (2x)
	PhaseType_PHASE_TYPE_NIGHT         PhaseType = 20 // 夜晚（整体，用于批量模式）
	PhaseType_PHASE_TYPE_NIGHT_GUARD   PhaseType = 21 // 守卫阶段
	PhaseType_PHASE_TYPE_NIGHT_WOLF    PhaseType = 22 // 狼人阶段
	PhaseType_PHASE_TYPE_NIGHT_WITCH   PhaseType = 23 // 女巫阶段
	PhaseType_PHASE_TYPE_NIGHT_SEER    PhaseType = 24 // 预言家阶段
	PhaseType_PHASE_TYPE_NIGHT_RESOLVE PhaseType = 25 // 夜晚结算阶段（处理击杀、猎人触发等）
	PhaseType_PHASE_TYPE_NIGHT_HUNTER  PhaseType = 26 // 猎人阶段（被动触发）
	// 白天阶段 (3x)
	PhaseType_PHASE_TYPE_DAY        PhaseType = 30
	PhaseType_PHASE_TYPE_DAY_HUNTER PhaseType = 31 // 白天猎人阶段（被投票出局后触发）
	// 投票阶段 (4x)
	PhaseType_PHASE_TYPE_VOTE PhaseType = 40
	// 结束 (5x)
	PhaseType_PHASE_TYPE_END PhaseType = 50
)

// Enum value maps for PhaseType.
var (
	PhaseType_name = map[int32]string{
		0:  "PHASE_TYPE_UNSPECIFIED",
		10: "PHASE_TYPE_START",
		20: "PHASE_TYPE_NIGHT",
		21: "PHASE_TYPE_NIGHT_GUARD",
		22: "PHASE_TYPE_NIGHT_WOLF",
		23: "PHASE_TYPE_NIGHT_WITCH",
		24: "PHASE_TYPE_NIGHT_SEER",
		25: "PHASE_TYPE_NIGHT_RESOLVE",
		26: "PHASE_TYPE_NIGHT_HUNTER",
		30: "PHASE_TYPE_DAY",
		31: "PHASE_TYPE_DAY_HUNTER",
		40: "PHASE_TYPE_VOTE",
		50: "PHASE_TYPE_END",
	}
	PhaseType_value = map[string]int32{
		"PHASE_TYPE_UNSPECIFIED":   0,
		"PHASE_TYPE_START":         10,
		"PHASE_TYPE_NIGHT":         20,
		"PHASE_TYPE_NIGHT_GUARD":   21,
		"PHASE_TYPE_NIGHT_WOLF":    22,
		"PHASE_TYPE_NIGHT_WITCH":   23,
		"PHASE_TYPE_NIGHT_SEER":    24,
		"PHASE_TYPE_NIGHT_RESOLVE": 25,
		"PHASE_TYPE_NIGHT_HUNTER":  26,
		"PHASE_TYPE_DAY":           30,
		"PHASE_TYPE_DAY_HUNTER":    31,
		"PHASE_TYPE_VOTE":          40,
		"PHASE_TYPE_END":           50,
	}
)

func (x PhaseType) Enum() *PhaseType {
	p := new(PhaseType)
	*p = x
	return p
}

func (x PhaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[0].Descriptor()
}

func (PhaseType) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[0]
}

func (x PhaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseType.Descriptor instead.
func (PhaseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

// Camp 阵营
type Camp int32

const (
	Camp_CAMP_UNSPECIFIED Camp = 0
	Camp_CAMP_GOOD        Camp = 1
	Camp_CAMP_EVIL        Camp = 2
)

// Enum value maps for Camp.
var (
	Camp_name = map[int32]string{
		0: "CAMP_UNSPECIFIED",
		1: "CAMP_GOOD",
		2: "CAMP_EVIL",
	}
	Camp_value = map[string]int32{
		"CAMP_UNSPECIFIED": 0,
		"CAMP_GOOD":        1,
		"CAMP_EVIL":        2,
	}
)

func (x Camp) Enum() *Camp {
	p := new(Camp)
	*p = x
	return p
}

func (x Camp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Camp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[1].Descriptor()
}

func (Camp) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[1]
}

func (x Camp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Camp.Descriptor instead.
func (Camp) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{1}
}

// RoleType 角色类型
type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSPECIFIED RoleType = 0
	RoleType_ROLE_TYPE_GOD         RoleType = 1 // 上帝（系统角色，用于发送公告）
	RoleType_ROLE_TYPE_WEREWOLF    RoleType = 2
	RoleType_ROLE_TYPE_SEER        RoleType = 3
	RoleType_ROLE_TYPE_WITCH       RoleType = 4
	RoleType_ROLE_TYPE_HUNTER      RoleType = 5
	RoleType_ROLE_TYPE_VILLAGER    RoleType = 6
	RoleType_ROLE_TYPE_GUARD       RoleType = 7
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNSPECIFIED",
		1: "ROLE_TYPE_GOD",
		2: "ROLE_TYPE_WEREWOLF",
		3: "ROLE_TYPE_SEER",
		4: "ROLE_TYPE_WITCH",
		5: "ROLE_TYPE_HUNTER",
		6: "ROLE_TYPE_VILLAGER",
		7: "ROLE_TYPE_GUARD",
	}
	RoleType_value = map[string]int32{
		"ROLE_TYPE_UNSPECIFIED": 0,
		"ROLE_TYPE_GOD":         1,
		"ROLE_TYPE_WEREWOLF":    2,
		"ROLE_TYPE_SEER":        3,
		"ROLE_TYPE_WITCH":       4,
		"ROLE_TYPE_HUNTER":      5,
		"ROLE_TYPE_VILLAGER":    6,
		"ROLE_TYPE_GUARD":       7,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[2].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[2]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{2}
}

// SkillType 技能类型
type SkillType int32

const (
	SkillType_SKILL_TYPE_UNSPECIFIED SkillType = 0
	SkillType_SKILL_TYPE_KILL        SkillType = 1  // 狼人击杀
	SkillType_SKILL_TYPE_CHECK       SkillType = 2  // 预言家查验
	SkillType_SKILL_TYPE_PROTECT     SkillType = 3  // 守卫保护
	SkillType_SKILL_TYPE_ANTIDOTE    SkillType = 4  // 女巫解药
	SkillType_SKILL_TYPE_POISON      SkillType = 5  // 女巫毒药
	SkillType_SKILL_TYPE_VOTE        SkillType = 6  // 投票
	SkillType_SKILL_TYPE_SPEAK       SkillType = 7  // 发言
	SkillType_SKILL_TYPE_SHOOT       SkillType = 8  // 猎人开枪
	SkillType_SKILL_TYPE_ANNOUNCE    SkillType = 9  // 上帝公告
	SkillType_SKILL_TYPE_SKIP        SkillType = 10 // 跳过行动（主动放弃技能使用）
)

// Enum value maps for SkillType.
var (
	SkillType_name = map[int32]string{
		0:  "SKILL_TYPE_UNSPECIFIED",
		1:  "SKILL_TYPE_KILL",
		2:  "SKILL_TYPE_CHECK",
		3:  "SKILL_TYPE_PROTECT",
		4:  "SKILL_TYPE_ANTIDOTE",
		5:  "SKILL_TYPE_POISON",
		6:  "SKILL_TYPE_VOTE",
		7:  "SKILL_TYPE_SPEAK",
		8:  "SKILL_TYPE_SHOOT",
		9:  "SKILL_TYPE_ANNOUNCE",
		10: "SKILL_TYPE_SKIP",
	}
	SkillType_value = map[string]int32{
		"SKILL_TYPE_UNSPECIFIED": 0,
		"SKILL_TYPE_KILL":        1,
		"SKILL_TYPE_CHECK":       2,
		"SKILL_TYPE_PROTECT":     3,
		"SKILL_TYPE_ANTIDOTE":    4,
		"SKILL_TYPE_POISON":      5,
		"SKILL_TYPE_VOTE":        6,
		"SKILL_TYPE_SPEAK":       7,
		"SKILL_TYPE_SHOOT":       8,
		"SKILL_TYPE_ANNOUNCE":    9,
		"SKILL_TYPE_SKIP":        10,
	}
)

func (x SkillType) Enum() *SkillType {
	p := new(SkillType)
	*p = x
	return p
}

func (x SkillType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[3].Descriptor()
}

func (SkillType) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[3]
}

func (x SkillType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillType.Descriptor instead.
func (SkillType) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{3}
}

// EventType 事件/效果类型
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// 游戏生命周期
	EventType_EVENT_TYPE_GAME_STARTED EventType = 1
	EventType_EVENT_TYPE_GAME_ENDED   EventType = 2
	// 技能效果（外部可见）
	EventType_EVENT_TYPE_KILL      EventType = 3  // 狼人击杀
	EventType_EVENT_TYPE_PROTECT   EventType = 4  // 守卫保护
	EventType_EVENT_TYPE_SAVE      EventType = 5  // 女巫救人
	EventType_EVENT_TYPE_POISON    EventType = 6  // 女巫毒杀
	EventType_EVENT_TYPE_CHECK     EventType = 7  // 预言家查验
	EventType_EVENT_TYPE_ELIMINATE EventType = 8  // 投票出局
	EventType_EVENT_TYPE_SHOOT     EventType = 9  // 猎人开枪
	EventType_EVENT_TYPE_SKIP      EventType = 10 // 跳过行动
	// 内部状态变更（不对外发布）
	EventType_EVENT_TYPE_SET_NIGHT_KILL     EventType = 100 // 设置夜晚击杀目标
	EventType_EVENT_TYPE_CLEAR_NIGHT_KILL   EventType = 101 // 清除夜晚击杀目标（被救）
	EventType_EVENT_TYPE_SET_LAST_PROTECTED EventType = 102 // 设置守卫上回合保护目标
	EventType_EVENT_TYPE_USE_ANTIDOTE       EventType = 103 // 消耗解药
	EventType_EVENT_TYPE_USE_POISON         EventType = 104 // 消耗毒药
	EventType_EVENT_TYPE_HUNTER_TRIGGERED   EventType = 105 // 猎人技能触发（死亡时）
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:   "EVENT_TYPE_UNSPECIFIED",
		1:   "EVENT_TYPE_GAME_STARTED",
		2:   "EVENT_TYPE_GAME_ENDED",
		3:   "EVENT_TYPE_KILL",
		4:   "EVENT_TYPE_PROTECT",
		5:   "EVENT_TYPE_SAVE",
		6:   "EVENT_TYPE_POISON",
		7:   "EVENT_TYPE_CHECK",
		8:   "EVENT_TYPE_ELIMINATE",
		9:   "EVENT_TYPE_SHOOT",
		10:  "EVENT_TYPE_SKIP",
		100: "EVENT_TYPE_SET_NIGHT_KILL",
		101: "EVENT_TYPE_CLEAR_NIGHT_KILL",
		102: "EVENT_TYPE_SET_LAST_PROTECTED",
		103: "EVENT_TYPE_USE_ANTIDOTE",
		104: "EVENT_TYPE_USE_POISON",
		105: "EVENT_TYPE_HUNTER_TRIGGERED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_TYPE_GAME_STARTED":       1,
		"EVENT_TYPE_GAME_ENDED":         2,
		"EVENT_TYPE_KILL":               3,
		"EVENT_TYPE_PROTECT":            4,
		"EVENT_TYPE_SAVE":               5,
		"EVENT_TYPE_POISON":             6,
		"EVENT_TYPE_CHECK":              7,
		"EVENT_TYPE_ELIMINATE":          8,
		"EVENT_TYPE_SHOOT":              9,
		"EVENT_TYPE_SKIP":               10,
		"EVENT_TYPE_SET_NIGHT_KILL":     100,
		"EVENT_TYPE_CLEAR_NIGHT_KILL":   101,
		"EVENT_TYPE_SET_LAST_PROTECTED": 102,
		"EVENT_TYPE_USE_ANTIDOTE":       103,
		"EVENT_TYPE_USE_POISON":         104,
		"EVENT_TYPE_HUNTER_TRIGGERED":   105,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[4].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[4]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{4}
}

// ErrorCode 错误码
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_PLAYER_NOT_FOUND    ErrorCode = 1 // 玩家未找到
	ErrorCode_ERROR_CODE_PLAYER_DEAD         ErrorCode = 2 // 玩家已死亡
	ErrorCode_ERROR_CODE_TARGET_NOT_FOUND    ErrorCode = 3 // 目标未找到
	ErrorCode_ERROR_CODE_TARGET_DEAD         ErrorCode = 4 // 目标已死亡
	ErrorCode_ERROR_CODE_SKILL_NOT_ALLOWED   ErrorCode = 5 // 技能不允许在此阶段使用
	ErrorCode_ERROR_CODE_GAME_NOT_STARTED    ErrorCode = 6 // 游戏未开始
	ErrorCode_ERROR_CODE_GAME_ENDED          ErrorCode = 7 // 游戏已结束
	ErrorCode_ERROR_CODE_INVALID_PHASE       ErrorCode = 8 // 无效阶段
	ErrorCode_ERROR_CODE_MESSAGE_NOT_ALLOWED ErrorCode = 9 // 当前阶段不允许发言
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_PLAYER_NOT_FOUND",
		2: "ERROR_CODE_PLAYER_DEAD",
		3: "ERROR_CODE_TARGET_NOT_FOUND",
		4: "ERROR_CODE_TARGET_DEAD",
		5: "ERROR_CODE_SKILL_NOT_ALLOWED",
		6: "ERROR_CODE_GAME_NOT_STARTED",
		7: "ERROR_CODE_GAME_ENDED",
		8: "ERROR_CODE_INVALID_PHASE",
		9: "ERROR_CODE_MESSAGE_NOT_ALLOWED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_PLAYER_NOT_FOUND":    1,
		"ERROR_CODE_PLAYER_DEAD":         2,
		"ERROR_CODE_TARGET_NOT_FOUND":    3,
		"ERROR_CODE_TARGET_DEAD":         4,
		"ERROR_CODE_SKILL_NOT_ALLOWED":   5,
		"ERROR_CODE_GAME_NOT_STARTED":    6,
		"ERROR_CODE_GAME_ENDED":          7,
		"ERROR_CODE_INVALID_PHASE":       8,
		"ERROR_CODE_MESSAGE_NOT_ALLOWED": 9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_event_proto_enumTypes[5].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_event_proto_enumTypes[5]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{5}
}

// Event 游戏事件（轻量级，用于外部通知）
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=werewolf.EventType" json:"type,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                                                   // 事件来源玩家
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                   // 事件目标玩家
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Event) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Event) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_event_proto protoreflect.FileDescriptor

const file_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x11proto/event.proto\x12\bwerewolf\"\xd2\x01\n" +
	"\x05Event\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.werewolf.EventTypeR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12-\n" +
	"\x04data\x18\x04 \x03(\v2\x19.werewolf.Event.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd4\x02\n" +
	"\tPhaseType\x12\x1a\n" +
	"\x16PHASE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PHASE_TYPE_START\x10\n" +
	"\x12\x14\n" +
	"\x10PHASE_TYPE_NIGHT\x10\x14\x12\x1a\n" +
	"\x16PHASE_TYPE_NIGHT_GUARD\x10\x15\x12\x19\n" +
	"\x15PHASE_TYPE_NIGHT_WOLF\x10\x16\x12\x1a\n" +
	"\x16PHASE_TYPE_NIGHT_WITCH\x10\x17\x12\x19\n" +
	"\x15PHASE_TYPE_NIGHT_SEER\x10\x18\x12\x1c\n" +
	"\x18PHASE_TYPE_NIGHT_RESOLVE\x10\x19\x12\x1b\n" +
	"\x17PHASE_TYPE_NIGHT_HUNTER\x10\x1a\x12\x12\n" +
	"\x0ePHASE_TYPE_DAY\x10\x1e\x12\x19\n" +
	"\x15PHASE_TYPE_DAY_HUNTER\x10\x1f\x12\x13\n" +
	"\x0fPHASE_TYPE_VOTE\x10(\x12\x12\n" +
	"\x0ePHASE_TYPE_END\x102*:\n" +
	"\x04Camp\x12\x14\n" +
	"\x10CAMP_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCAMP_GOOD\x10\x01\x12\r\n" +
	"\tCAMP_EVIL\x10\x02*\xbc\x01\n" +
	"\bRoleType\x12\x19\n" +
	"\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rROLE_TYPE_GOD\x10\x01\x12\x16\n" +
	"\x12ROLE_TYPE_WEREWOLF\x10\x02\x12\x12\n" +
	"\x0eROLE_TYPE_SEER\x10\x03\x12\x13\n" +
	"\x0fROLE_TYPE_WITCH\x10\x04\x12\x14\n" +
	"\x10ROLE_TYPE_HUNTER\x10\x05\x12\x16\n" +
	"\x12ROLE_TYPE_VILLAGER\x10\x06\x12\x13\n" +
	"\x0fROLE_TYPE_GUARD\x10\a*\x89\x02\n" +
	"\tSkillType\x12\x1a\n" +
	"\x16SKILL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSKILL_TYPE_KILL\x10\x01\x12\x14\n" +
	"\x10SKILL_TYPE_CHECK\x10\x02\x12\x16\n" +
	"\x12SKILL_TYPE_PROTECT\x10\x03\x12\x17\n" +
	"\x13SKILL_TYPE_ANTIDOTE\x10\x04\x12\x15\n" +
	"\x11SKILL_TYPE_POISON\x10\x05\x12\x13\n" +
	"\x0fSKILL_TYPE_VOTE\x10\x06\x12\x14\n" +
	"\x10SKILL_TYPE_SPEAK\x10\a\x12\x14\n" +
	"\x10SKILL_TYPE_SHOOT\x10\b\x12\x17\n" +
	"\x13SKILL_TYPE_ANNOUNCE\x10\t\x12\x13\n" +
	"\x0fSKILL_TYPE_SKIP\x10\n" +
	"*\xcf\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_GAME_STARTED\x10\x01\x12\x19\n" +
	"\x15EVENT_TYPE_GAME_ENDED\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_KILL\x10\x03\x12\x16\n" +
	"\x12EVENT_TYPE_PROTECT\x10\x04\x12\x13\n" +
	"\x0fEVENT_TYPE_SAVE\x10\x05\x12\x15\n" +
	"\x11EVENT_TYPE_POISON\x10\x06\x12\x14\n" +
	"\x10EVENT_TYPE_CHECK\x10\a\x12\x18\n" +
	"\x14EVENT_TYPE_ELIMINATE\x10\b\x12\x14\n" +
	"\x10EVENT_TYPE_SHOOT\x10\t\x12\x13\n" +
	"\x0fEVENT_TYPE_SKIP\x10\n" +
	"\x12\x1d\n" +
	"\x19EVENT_TYPE_SET_NIGHT_KILL\x10d\x12\x1f\n" +
	"\x1bEVENT_TYPE_CLEAR_NIGHT_KILL\x10e\x12!\n" +
	"\x1dEVENT_TYPE_SET_LAST_PROTECTED\x10f\x12\x1b\n" +
	"\x17EVENT_TYPE_USE_ANTIDOTE\x10g\x12\x19\n" +
	"\x15EVENT_TYPE_USE_POISON\x10h\x12\x1f\n" +
	"\x1bEVENT_TYPE_HUNTER_TRIGGERED\x10i*\xc1\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_PLAYER_NOT_FOUND\x10\x01\x12\x1a\n" +
	"\x16ERROR_CODE_PLAYER_DEAD\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_TARGET_NOT_FOUND\x10\x03\x12\x1a\n" +
	"\x16ERROR_CODE_TARGET_DEAD\x10\x04\x12 \n" +
	"\x1cERROR_CODE_SKILL_NOT_ALLOWED\x10\x05\x12\x1f\n" +
	"\x1bERROR_CODE_GAME_NOT_STARTED\x10\x06\x12\x19\n" +
	"\x15ERROR_CODE_GAME_ENDED\x10\a\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_PHASE\x10\b\x12\"\n" +
	"\x1eERROR_CODE_MESSAGE_NOT_ALLOWED\x10\tB#Z!github.com/Zereker/werewolf/protob\x06proto3"

var (
	file_proto_event_proto_rawDescOnce sync.Once
	file_proto_event_proto_rawDescData []byte
)

func file_proto_event_proto_rawDescGZIP() []byte {
	file_proto_event_proto_rawDescOnce.Do(func() {
		file_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)))
	})
	return file_proto_event_proto_rawDescData
}

var file_proto_event_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_event_proto_goTypes = []any{
	(PhaseType)(0), // 0: werewolf.PhaseType
	(Camp)(0),      // 1: werewolf.Camp
	(RoleType)(0),  // 2: werewolf.RoleType
	(SkillType)(0), // 3: werewolf.SkillType
	(EventType)(0), // 4: werewolf.EventType
	(ErrorCode)(0), // 5: werewolf.ErrorCode
	(*Event)(nil),  // 6: werewolf.Event
	nil,            // 7: werewolf.Event.DataEntry
}
var file_proto_event_proto_depIdxs = []int32{
	4, // 0: werewolf.Event.type:type_name -> werewolf.EventType
	7, // 1: werewolf.Event.data:type_name -> werewolf.Event.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_event_proto_init() }
func file_proto_event_proto_init() {
	if File_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_event_proto_goTypes,
		DependencyIndexes: file_proto_event_proto_depIdxs,
		EnumInfos:         file_proto_event_proto_enumTypes,
		MessageInfos:      file_proto_event_proto_msgTypes,
	}.Build()
	File_proto_event_proto = out.File
	file_proto_event_proto_goTypes = nil
	file_proto_event_proto_depIdxs = nil
}
